const {chromium}=require('../_pw');
const H=require('../harness'), APP=H.APP;
(async()=>{
  const b=await chromium.launch();
  const p=await b.newPage({viewport:{width:1500,height:950}});
  const errs=[]; p.on('pageerror',e=>errs.push(String(e).slice(0,200)));
  await p.goto('file://'+APP); await p.waitForTimeout(1000);
  await p.evaluate(()=>window.__hook().createProject()); await p.waitForTimeout(700);
  const sh=await p.$('text=Sheet 01'); if(sh&&await sh.isVisible()) await sh.click();
  await p.waitForTimeout(400);
  await p.click('#btnImport'); await p.setInputFiles('#fileInput', H.fixture('ang_mirror.dxf'));
  await p.waitForTimeout(2200);
  await p.click('#btnStylize'); await p.waitForTimeout(2200);
  const sel=()=>p.evaluate(()=>{ const h=window.__hook();
    const pg=h.store.pages.find(x=>x.id===h.store.activeId);
    const m=(h.dimModels(pg)||[]).filter(x=>x.kind==='angular')[0];
    h.setSelection((pg.objects||[]).filter(o=>(o.prims.polys||[]).some(q=>q._dim===m.id)
                                            ||(o.prims.texts||[]).some(t=>t._dim===m.id)).map(o=>o.id));
    h.render();
    const g=h.dimGeomOf(m);
    return {grips:(h.dimHandles? [] : []), text:[g.text.x,g.text.y], ta:m.text.ta, tr:m.text.tr}; });
  const S=async(wx,wy)=>{ const c=await p.evaluate(([x,y])=>{ const q=window.__hook().W2S(x,y);
    const r=document.getElementById('stage').getBoundingClientRect();
    return {x:r.left+q.x, y:r.top+q.y}; },[wx,wy]); return c; };
  const before=await sel();
  console.log('value at '+JSON.stringify(before.text)+'  ta='+before.ta+' tr='+before.tr);
  const a=await S(before.text[0], before.text[1]);
  const t=await S(before.text[0]+14, before.text[1]-12);
  await p.mouse.move(a.x,a.y); await p.waitForTimeout(120);
  console.log('what the cursor is over: '+JSON.stringify(await p.evaluate(([x,y])=>{
    const h=window.__hook(); const pg=h.store.pages.find(z=>z.id===h.store.activeId);
    const g=(h.dimStretchAt? h.dimStretchAt(x,y):null);
    return g? {kind:g.kind} : 'nothing'; }, before.text)));
  await p.mouse.down(); await p.mouse.move(t.x,t.y,{steps:10}); await p.mouse.up();
  await p.waitForTimeout(600);
  const after=await sel();
  console.log('value now  '+JSON.stringify(after.text)+'  ta='+after.ta+' tr='+after.tr);
  console.log('the value moved: '+(JSON.stringify(before.text)!==JSON.stringify(after.text)));
  if(errs.length) console.log('PAGE ERRORS: '+errs.join(' | '));
  await b.close();
})();
