const {chromium}=require('../_pw');
const H=require('../harness'), APP=H.APP;
const fs=require('fs'), path=require('path');
const OUT=path.join(H.ROOT,'tests','out'); fs.mkdirSync(OUT,{recursive:true});
(async()=>{
  const b=await chromium.launch();
  const p=await b.newPage({viewport:{width:1500,height:950}});
  await p.goto('file://'+APP); await p.waitForTimeout(900);
  await p.evaluate(()=>window.__hook().createProject()); await p.waitForTimeout(800);
  const sh=await p.$('text=Sheet 01'); if(sh&&await sh.isVisible()) await sh.click();
  await p.waitForTimeout(600);
  const pt=await p.evaluate(()=>{ const h=window.__hook(), st=h.store, m=st.format.margin;
    const P={A4:[297,210],A3:[420,297],A2:[594,420]}[st.format.paper];
    const c=h.W2S(P[0]-m-170/2, m+24.68/2);
    const r=document.getElementById('stage').getBoundingClientRect();
    return {x:r.left+c.x, y:r.top+c.y}; });
  await p.mouse.dblclick(pt.x, pt.y); await p.waitForTimeout(600);
  await p.fill('#tbTitle','gear housing plate'); await p.waitForTimeout(400);
  const saved=await p.$('#rpSave'); if(saved) { await saved.click(); await p.waitForTimeout(700); }
  const r=await p.evaluate(()=>{ const h=window.__hook();
    const pg=h.store.pages.find(x=>x.type==='sheet');
    const typed=pg.title.title;
    const drawn=h.captureSheet(pg).filter(e=>e.t==='text').map(e=>e.text);
    return {typed, hit:drawn.filter(t=>/GEAR|gear/i.test(t))};
  });
  console.log('typed into the field : "'+r.typed+'"');
  console.log('drawn on the sheet   : '+JSON.stringify(r.hit));
  await p.waitForTimeout(400);
  fs.writeFileSync(path.join(OUT,'ui_upper.png'), await p.locator('#stage').screenshot());
  await b.close();
})();
